module.exports = [
  {
    shipment_id: "SH0001",
    tracking_number: "TN123456",
    shipper: "Company A",
    receiver: "Company X",
    product: "Widget",
    quantity: 100,
    destination: "New York, NY",
  },
  {
    shipment_id: "SH0002",
    tracking_number: "TN234567",
    shipper: "Company B",
    receiver: "Company Y",
    product: "Gadget",
    quantity: 50,
    destination: "Los Angeles, CA",
  },
  {
    shipment_id: "SH0003",
    tracking_number: "TN345678",
    shipper: "Company C",
    receiver: "Company Z",
    product: "Tool",
    quantity: 75,
    destination: "Chicago, IL",
  },
  {
    shipment_id: "SH0004",
    tracking_number: "TN456789",
    shipper: "Company D",
    receiver: "Company X",
    product: "Widget",
    quantity: 200,
    destination: "Houston, TX",
  },
  {
    shipment_id: "SH0005",
    tracking_number: "TN567890",
    shipper: "Company E",
    receiver: "Company Y",
    product: "Gadget",
    quantity: 60,
    destination: "Philadelphia, PA",
  },
  {
    shipment_id: "SH0006",
    tracking_number: "TN678901",
    shipper: "Company F",
    receiver: "Company Z",
    product: "Tool",
    quantity: 90,
    destination: "Phoenix, AZ",
  },
  {
    shipment_id: "SH0007",
    tracking_number: "TN789012",
    shipper: "Company G",
    receiver: "Company X",
    product: "Widget",
    quantity: 150,
    destination: "San Antonio, TX",
  },
  {
    shipment_id: "SH0008",
    tracking_number: "TN890123",
    shipper: "Company H",
    receiver: "Company Y",
    product: "Gadget",
    quantity: 70,
    destination: "San Diego, CA",
  },
  {
    shipment_id: "SH0009",
    tracking_number: "TN901234",
    shipper: "Company I",
    receiver: "Company Z",
    product: "Tool",
    quantity: 80,
    destination: "Dallas, TX",
  },
  {
    shipment_id: "SH0010",
    tracking_number: "TN010101",
    shipper: "Company J",
    receiver: "Company X",
    product: "Widget",
    quantity: 120,
    destination: "San Jose, CA",
  },
  {
    shipment_id: "SH0011",
    tracking_number: "TN020202",
    shipper: "Company K",
    receiver: "Company Y",
    product: "Gadget",
    quantity: 55,
    destination: "Austin, TX",
  },
  {
    shipment_id: "SH0012",
    tracking_number: "TN030303",
    shipper: "Company L",
    receiver: "Company Z",
    product: "Tool",
    quantity: 70,
    destination: "Jacksonville, FL",
  },
  {
    shipment_id: "SH0013",
    tracking_number: "TN040404",
    shipper: "Company M",
    receiver: "Company X",
    product: "Widget",
    quantity: 180,
    destination: "Indianapolis, IN",
  },
  {
    shipment_id: "SH0014",
    tracking_number: "TN050505",
    shipper: "Company N",
    receiver: "Company Y",
    product: "Gadget",
    quantity: 45,
    destination: "San Francisco, CA",
  },
  {
    shipment_id: "SH0015",
    tracking_number: "TN060606",
    shipper: "Company O",
    receiver: "Company Z",
    product: "Tool",
    quantity: 85,
    destination: "Columbus, OH",
  },
  {
    shipment_id: "SH0016",
    tracking_number: "TN070707",
    shipper: "Company P",
    receiver: "Company X",
    product: "Widget",
    quantity: 130,
    destination: "Charlotte, NC",
  },
  {
    shipment_id: "SH0017",
    tracking_number: "TN080808",
    shipper: "Company Q",
    receiver: "Company Y",
    product: "Gadget",
    quantity: 65,
    destination: "Fort Worth, TX",
  },
  {
    shipment_id: "SH0018",
    tracking_number: "TN090909",
    shipper: "Company R",
    receiver: "Company Z",
    product: "Tool",
    quantity: 95,
    destination: "Detroit, MI",
  },
  {
    shipment_id: "SH0019",
    tracking_number: "TN101010",
    shipper: "Company S",
    receiver: "Company X",
    product: "Widget",
    quantity: 110,
    destination: "Memphis, TN",
  },
  {
    shipment_id: "SH0020",
    tracking_number: "TN111111",
    shipper: "Company T",
    receiver: "Company Y",
    product: "Gadget",
    quantity: 75,
    destination: "Boston, MA",
  },
];
